### ISSUE TITLE
Add Hotkey for Escaping/Resetting the Prompt

### ISSUE THREAD

**Issue by ranelpadon** [gennaro-tedesco/gh-s#1]
Maybe good idea to bind `Esc` key to escape/reset the prompt? For example, the user might want to change the search term but there's no way to change it except to quit the command (e.g. using `Ctrl-C`).

PS: Thanks for this nifty extension. :)

**Comment by gennaro-tedesco** [comment]
Yes, I am looking into it. It seems that `promptui` does allow for key [re-binding](https://github.com/manifoldco/promptui/blob/c2e487d3597f59bcf76b24c9e80679740a72212b/select.go#L87), however I must see if there is a way to reset the selection prompt without exiting the interface; in this respect we are limited by the scope of that framework (I will see if there is a way to achieve it nevertheless).
