### ISSUE TITLE
Support netbsd-amd64

### ISSUE THREAD

**Issue by pfr-dev** [gennaro-tedesco/gh-s#10]
title self explainatory

**Comment by gennaro-tedesco** [comment]
We are looking to integrate more architectures with Goreleaser: in particular see [this PR](https://github.com/gennaro-tedesco/gh-s/pull/11) and [v0.0.4](https://github.com/gennaro-tedesco/gh-s/releases/tag/v0.0.4).

I am checking whether Goreleaser supports `netbds` too (if you have any pointer feel free to suggest).

**Comment by gennaro-tedesco** [comment]
Added in [v0.0.6](https://github.com/gennaro-tedesco/gh-s/releases/tag/v0.0.6)

**Comment by pfr-dev** [comment]
Thanks, working now!
