### ISSUE TITLE
Arrow keys not working on powershell 7.2.1 with oh-my-posh (in case that could have any effect).

### ISSUE THREAD

**Issue by TerabyteRex** [gennaro-tedesco/gh-s#13]
I can reproduce this 100% of the time.
1) search
2) results display
3) cannot move cursor down the list.

**Comment by gennaro-tedesco** [comment]
Good morning and thank you for reporting. Before digging into it could you please check whether your problem is similar to https://github.com/gennaro-tedesco/gh-i/issues/3?

**Comment by TerabyteRex** [comment]
that is exactly my issue. I did not load on my posh and tried it. something else is causing the vimkey use. gh standalone has no issues. will look at promptui.

**Comment by TerabyteRex** [comment]
looks like its an issue with a library they are using
https://github.com/CircleCI-Public/circleci-cli/issues/501

**Comment by gennaro-tedesco** [comment]
I did not know about `survey`, I suppose it is then a nice alternative to `promptui`; since I am not familiar with it, I guess I would need the time to look into it before deciding whether or not to include it. 

The vim navigation keys however do work in your case, do they not? Would they not be sufficient to get by for the time being?

**Comment by TerabyteRex** [comment]
oh - to be clear - i love your extension and thank you so very much. I will use vim keys for now. The one interesting thing i saw in the other project is that they said prompui was slower on windows. I think that might be true.

Again thank you for all your work and will use vim keys for now. maybe i should learn go so i could help out :)

**Comment by gennaro-tedesco** [comment]
Thank you for your kind words! I will keep the issue open for the time being whilst I assess the possibility to switch prompts: to be honest I wouldn't want to create versions incompatibilities (say users on other platforms or so), however I will check with `promptui` if they are planning to address this problem at some point (if so, we may just wait for a fix).

**Comment by ArkhamCookie** [comment]
> 

I never knew those keys had a name.  It's weird how easy it is to never learn the small things like that.  I'm also having this issue, but I assume it is that something is conflicting with it.  Trying out a new set-up, at the moment.  Definitely not a big deal, and want to make it clear I also really like the extension.  It's very clean and does exactly what it needs to do.  An interesting solution could be making all the choices also be clickable links, but I don't know if that would affect other things negatively.  I've never really used GO or made Github-Cl extensions.
