### ISSUE TITLE
Support darwin-arm64

### ISSUE THREAD

**Issue by docgonzo2015** [gennaro-tedesco/gh-s#2]

**Comment by gennaro-tedesco** [comment]
The distributions releases are built automatically by [this GitHub action](https://github.com/gennaro-tedesco/gh-s/blob/master/.github/workflows/release.yml) and I do see that `darwin/arm64` is in fact missing. Looking around [here](https://github.com/golang/go/issues/49889) and [here](https://github.com/goreleaser/goreleaser/issues/1952) it seems that this discussion is in place in Go as a whole (so not available yet).

If you however do have pointers on how this can be achieved manually I would be happy to look into it (I am not an expert on the matter myself, so I am reading around to see how to achieve it)!

**Comment by seachicken** [comment]
We can support darwin-arm64 by using Goreleaser instead.
Sample:
https://github.com/seachicken/gh-poi/blob/8536479ffcee9b6ad040e33d8d943bf6f8f2bc9e/.github/workflows/release.yml#L24
https://github.com/seachicken/gh-poi/releases/tag/v0.3.1

Or we may have to wait for a new version to be released.
https://github.com/cli/gh-extension-precompile/pull/3#issuecomment-984863733

**Comment by gennaro-tedesco** [comment]
Thank you for pointing to the right direction! I would personally prefer to wait for a new version to be released: this is because then we would be dependent on an additional dependency, it being Goreleaser. What has been your experience with it? From the snippet you provided I take it is just a matter of changing the action file workflow?

**Comment by seachicken** [comment]
In order for Goreleaser to work, you need to add GitHub Actions and yml.
https://github.com/seachicken/gh-poi/blob/main/.goreleaser.yml

I've been using this for a few months now and it seems to work perfectly fine.
However, I would like to use what the official version provides as much as possible, so I will replace it when the cli/gh-extension-precompile is upgraded. Until then, it's not a bad alternative.

**Comment by gennaro-tedesco** [comment]
Again thank you for the complete set of instructions :).

Since I do not own a `darwin-arm64` architecture I would need someone to help test on theirs that the produced release works. So for anyone passing by this issue with such system, feel free to open a PR.

**Comment by gennaro-tedesco** [comment]
Courtesy of @seachicken now [v0.0.4](https://github.com/gennaro-tedesco/gh-s/releases/tag/v0.0.4) has support for `darwin-arm64` too. 

@docgonzo2015 would you try to see if it works for you too?

**Comment by mislav** [comment]
The [latest GitHub CLI 2.8.0 release](https://github.com/cli/cli/releases/tag/v2.8.0) fixes this by falling back to `amd64` binary if Rosetta is installed. If an `arm64` binary is found, for example as a product of the [latest gh-extension-precompile action](https://github.com/cli/gh-extension-precompile/releases/tag/v1.1.2), however, then its codesigning is fixed after downloading to allow execution by the OS.
