### ISSUE TITLE
Feature Request: Search for (multiple) topics?

### ISSUE THREAD

**Issue by StevenACoffman** [gennaro-tedesco/gh-s#3]
I like to search for multiple topics `topic:go topic:ecs` in addition to narrowing searches by language. It would be nice if there was a flag that could be specified multiple times.

Thanks for a handy tool!

**Comment by gennaro-tedesco** [comment]
Are you sure it is possible to search for multiple topics at the same time? Referring to [the docs](https://docs.github.com/en/search-github/searching-on-github/searching-for-repositories#search-by-topic) and quickly trying myself seems to always give 
```
{
  "total_count": 0,
  "incomplete_results": false,
  "items": []
}
```
(unless I am by accident making calls that always return zero). The arguments (and flags) are being handed over to GitHub query calls as [per here](https://github.com/gennaro-tedesco/gh-s/blob/2957b8bd53d41af3d31d854c1e3357aa0a9e4d9d/cmd/ui.go#L34). Do you have an example of what a query for multiple topics looks like?

Of course one thing that is a no-brainer is to create a flag `-t` to at least include one topic (which at the moment I missed).

**Comment by StevenACoffman** [comment]
Since you are using cobra and viper, I think you can do it like this:
> ```go
func NewCommand() *cobra.Command {
	var slice []string
	var arr []string
	c := &cobra.Command{
		Use:  "cmd",
		Run: func(cmd *cobra.Command, args []string) {
			for _, v := range slice {
				fmt.Println(v)
			}

			for _, v := range arr {
				fmt.Println(v)
			}
		},
	}


	c.Flags().StringSliceVarP(&slice, "slice", "s", []string{}, "")
	c.Flags().StringArrayVarP(&arr, "arr", "a", []string{}, "")

	return c
}

func main() {
       NewCommand().Execute()
}
```

```
$ cmd --slice a --slice b --slice c,d,e
a
b
c
d
e
```

```
$ cmd --arr a --arr b --arr c,d,e
a
b
c,d,e
```
using `--topic="one" --topic="two,three"` as an example:

* `StringSlice*` - will result in `[]string{"one", "two", "three"}`
* `StringArray*` - will result in `[]string{"one", "two,three"}`

Learn more at:

* https://godoc.org/github.com/spf13/pflag#StringArray
* https://godoc.org/github.com/spf13/pflag#StringSlice

**Comment by StevenACoffman** [comment]
To search for multiple topics on github, you can do this 

The Github.com ui currently does not intuitively facilitate searching for multiple topics without workarounds but search GitHub like entering "topic:go topic:ecs" so it will do this: https://github.com/search?q=topic%3Ago+topic%3Aecs. However their api allows you to query multiple tags. Below is a simple example to query github.com with `ecs` and `go` topic tags.
```
curl -H "Accept: application/vnd.github.mercy-preview+json" \
https://api.github.com/search/repositories?q=topic:ecs+topic:go
```

**Comment by gennaro-tedesco** [comment]
I see, yes, it makes sense and it should be feasible, I will have a go at it between today and tomorrow. However, notice that 
```
q=topic:ecs+topic:go
```
filters for topics `ecs` and `go` in the _same repository_, not instead fetching the union of repositories containing the former and the latter: is this the intended behaviour you suggested?

**Comment by StevenACoffman** [comment]
Yes, for me at at least.  I am generally trying to further narrow search results with more topics, rather than expand them.

I am pretty sure the default search works as though there is an implied AND operator between each search key-value pair.

**Comment by gennaro-tedesco** [comment]
> I am pretty sure the default search works as though there is an implied AND operator between each search key-value pair.

Strangely enough for `topic` it behaves as an AND but for `language` it behaves like an OR. For instance
```
# returns non-zero results since (go OR lua = TRUE)
gh api -X GET /search/repositories -f q='promptui in:name language:go language:lua'
```
```
returns zero results since (cli AND random = FALSE) even though (cli OR random = TRUE)
gh api -X GET /search/repositories -f q='promptui in:name topic:cli topic:random'
```
However, I might have a working draft soon: would you be so kind to help me test it, if it is not too big of an ask (essentially clone the branch and install it locally to make sure it does what you intend)?

**Comment by gennaro-tedesco** [comment]
In particular [this is](https://github.com/gennaro-tedesco/gh-s/pull/4) the corresponding PR.

**Comment by gennaro-tedesco** [comment]
[v0.0.2](https://github.com/gennaro-tedesco/gh-s/releases/tag/v0.0.2) with this change is released: you can now `gh extension upgrade s` to have the latest :)

Notice another small change I added, namely the possibility to handle `stdout/stdin` to pipe `gh s` into generic other commands: have a look at some examples in the [wiki](https://github.com/gennaro-tedesco/gh-s/wiki/Execute-commands).

And most importantly thank you for taking the time to look into this with me! 🙏🏼
